"""LaTeX generator for Lean 4 proofs."""

from pathlib import Path

from narrate_lean.parser import LeanDocument


class LaTeXGenerator:
    """Generator for LaTeX documents from Lean proofs."""

    def __init__(self) -> None:
        """Initialize the LaTeX generator."""
        pass

    def generate(self, document: LeanDocument, output_path: Path) -> None:
        """Generate a LaTeX document from a parsed Lean document.

        Args:
            document: Parsed Lean document
            output_path: Path to write the output LaTeX file
        """
        latex_content = self._build_latex(document)
        output_path.write_text(latex_content)

    def _build_latex(self, document: LeanDocument) -> str:
        """Build the LaTeX content from a Lean document.

        Args:
            document: Parsed Lean document

        Returns:
            LaTeX formatted string
        """
        sections = []

        # Document header
        sections.append(self._generate_header())

        # Add theorems section
        if document.theorems:
            sections.append(r"\section{Theorems}")
            sections.append("")
            for theorem in document.theorems:
                sections.append(self._format_theorem(theorem))
                sections.append("")

        # Add definitions section
        if document.definitions:
            sections.append(r"\section{Definitions}")
            sections.append("")
            for definition in document.definitions:
                sections.append(self._format_definition(definition))
                sections.append("")

        # Document footer
        sections.append(self._generate_footer())

        return "\n".join(sections)

    def _generate_header(self) -> str:
        """Generate the LaTeX document header.

        Returns:
            LaTeX header string
        """
        return r"""\documentclass{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{amsthm}
\usepackage{listings}
\usepackage{xcolor}

\theoremstyle{plain}
\newtheorem{theorem}{Theorem}
\newtheorem{definition}{Definition}

\lstdefinestyle{leanstyle}{
    language=C,
    basicstyle=\ttfamily\small,
    keywordstyle=\color{blue},
    commentstyle=\color{green!60!black},
    stringstyle=\color{red},
    breaklines=true,
    frame=single,
    numbers=left,
    numberstyle=\tiny\color{gray}
}

\title{Lean 4 Proof Documentation}
\author{Generated by narrate-lean}
\date{\today}

\begin{document}

\maketitle"""

    def _generate_footer(self) -> str:
        """Generate the LaTeX document footer.

        Returns:
            LaTeX footer string
        """
        return r"\end{document}"

    def _format_theorem(self, theorem) -> str:
        """Format a theorem in LaTeX.

        Args:
            theorem: LeanTheorem object

        Returns:
            LaTeX formatted theorem
        """
        # Clean and format the statement
        statement = self._escape_latex(theorem.statement)
        proof_text = self._escape_latex(theorem.proof)

        latex = [
            r"\begin{theorem}[" + self._escape_latex(theorem.name) + "]",
            statement,
            r"\end{theorem}",
            "",
            r"\begin{proof}",
        ]

        if proof_text:
            latex.append(r"\begin{lstlisting}[style=leanstyle]")
            latex.append(proof_text)
            latex.append(r"\end{lstlisting}")
        else:
            latex.append("Proof omitted.")

        latex.append(r"\end{proof}")

        return "\n".join(latex)

    def _format_definition(self, definition) -> str:
        """Format a definition in LaTeX.

        Args:
            definition: LeanDefinition object

        Returns:
            LaTeX formatted definition
        """
        type_sig = self._escape_latex(definition.type_signature)
        body = self._escape_latex(definition.body)

        latex = [
            r"\begin{definition}[" + self._escape_latex(definition.name) + "]",
            type_sig,
            r"\end{definition}",
            "",
        ]

        if body:
            latex.append(r"\textbf{Definition:}")
            latex.append(r"\begin{lstlisting}[style=leanstyle]")
            latex.append(body)
            latex.append(r"\end{lstlisting}")

        return "\n".join(latex)

    def _escape_latex(self, text: str) -> str:
        """Escape special LaTeX characters.

        Args:
            text: Text to escape

        Returns:
            Escaped text
        """
        # Basic LaTeX escaping
        replacements = {
            "\\": r"\textbackslash{}",
            "{": r"\{",
            "}": r"\}",
            "$": r"\$",
            "&": r"\&",
            "%": r"\%",
            "#": r"\#",
            "_": r"\_",
            "~": r"\textasciitilde{}",
            "^": r"\textasciicircum{}",
        }

        result = text
        for char, replacement in replacements.items():
            result = result.replace(char, replacement)

        return result
