"""Markdown generator for Lean 4 proofs."""

from pathlib import Path

from narrate_lean.parser import LeanDocument


class MarkdownGenerator:
    """Generator for Markdown documents from Lean proofs."""

    def __init__(self) -> None:
        """Initialize the Markdown generator."""
        pass

    def generate(self, document: LeanDocument, output_path: Path) -> None:
        """Generate a Markdown document from a parsed Lean document.

        Args:
            document: Parsed Lean document
            output_path: Path to write the output Markdown file
        """
        markdown_content = self._build_markdown(document)
        output_path.write_text(markdown_content)

    def _build_markdown(self, document: LeanDocument) -> str:
        """Build the Markdown content from a Lean document.

        Args:
            document: Parsed Lean document

        Returns:
            Markdown formatted string
        """
        sections = []

        # Document header
        sections.append("# Lean 4 Proof Documentation")
        sections.append("")
        sections.append("*Generated by narrate-lean*")
        sections.append("")

        # Add theorems section
        if document.theorems:
            sections.append("## Theorems")
            sections.append("")
            for theorem in document.theorems:
                sections.append(self._format_theorem(theorem))
                sections.append("")

        # Add definitions section
        if document.definitions:
            sections.append("## Definitions")
            sections.append("")
            for definition in document.definitions:
                sections.append(self._format_definition(definition))
                sections.append("")

        return "\n".join(sections)

    def _format_theorem(self, theorem) -> str:
        """Format a theorem in Markdown.

        Args:
            theorem: LeanTheorem object

        Returns:
            Markdown formatted theorem
        """
        markdown = [
            f"### Theorem: {theorem.name}",
            "",
            "**Statement:**",
            "",
            "```lean",
            theorem.statement,
            "```",
            "",
        ]

        if theorem.proof:
            markdown.append("**Proof:**")
            markdown.append("")
            markdown.append("```lean")
            markdown.append(theorem.proof)
            markdown.append("```")
        else:
            markdown.append("**Proof:** *(omitted)*")

        return "\n".join(markdown)

    def _format_definition(self, definition) -> str:
        """Format a definition in Markdown.

        Args:
            definition: LeanDefinition object

        Returns:
            Markdown formatted definition
        """
        markdown = [
            f"### Definition: {definition.name}",
            "",
            "**Type:**",
            "",
            "```lean",
            definition.type_signature,
            "```",
            "",
        ]

        if definition.body:
            markdown.append("**Body:**")
            markdown.append("")
            markdown.append("```lean")
            markdown.append(definition.body)
            markdown.append("```")

        return "\n".join(markdown)
